import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  wrapper: {
    flex: 1,
    flexDirection: 'column',
    padding: 24,
    paddingBottom: 16,
    justifyContent: 'flex-end',
    gap: 16,
    position: 'relative',
  },
  row: {
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
    flexDirection: 'row',
  },
  line: {
    height: 1,
    backgroundColor: '#1e1e1e',
    marginVertical: 10,
    width: '39%',
  },
  text: {
    fontSize: 14,
    lineHeight: 20,
    color: '#fff',
    textAlign: 'center',
    fontFamily: 'NotoSans_400Regular',
  },
  emailInput: {
    width: '100%',
    paddingBottom: 10,
    paddingTop: 10,
    paddingLeft: 16,
    paddingRight: 16,
    backgroundColor: 'rgba(0,0,0,0.2)',
    borderRadius: 8,
    borderWidth: 1,
    borderBottomColor: '#1e1e1e',
    borderTopColor: '#1e1e1e',
    borderLeftColor: '#1e1e1e',
    borderRightColor: '#1e1e1e',
    color: 'white',
    fontFamily: 'NotoSans_400Regular',
    fontSize: 14,
  },
  inputError: {
    borderBottomColor: '#ff0000',
    borderTopColor: '#ff0000',
    borderLeftColor: '#ff0000',
    borderRightColor: '#ff0000',
  },
  row_otp: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  col_otp: {
    width: '8%',
    flexGrow: 1,
  },
  text_otp: {
    fontFamily: 'NotoSans_400Regular',
    fontSize: 14,
    color: '#373737'
  },
  input_otp: {
    paddingBottom: 10,
    paddingTop: 10,
    paddingLeft: 5,
    paddingRight: 5,
    backgroundColor: 'rgba(0,0,0,0.2)',
    borderRadius: 8,
    borderWidth: 1,
    borderBottomColor: '#1e1e1e',
    borderTopColor: '#1e1e1e',
    borderLeftColor: '#1e1e1e',
    borderRightColor: '#1e1e1e',
    textAlign: 'center',
    width: '100%',
    color: 'white',
    fontFamily: 'NotoSans_400Regular',
    fontSize: 16,
  },
  text_enter: {
    textAlign: 'center',
    fontFamily: 'NotoSans_400Regular',
    fontSize: 14,
    color: '#ffffff',
    marginBottom: 2,
  },
  text_email_code: {
    textAlign: 'center',
    fontFamily: 'NotoSans_400Regular',
    fontSize: 14,
    color: '#ffffff',
  },
  buttonBack: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
});