import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  wrapper: {
    flex: 1,
    flexDirection: 'column',
    padding: 24,
    justifyContent: 'flex-end',
    gap: 16,
    position: 'relative',
  },
  row: {

  },
  text: {
    fontSize: 14,
    lineHeight: 20,
    color: '#fff',
    textAlign: 'center',
    fontFamily: 'NotoSans_400Regular',
  },
  emailInput: {
    width: '100%',
    paddingBottom: 10,
    paddingTop: 10,
    paddingLeft: 16,
    paddingRight: 16,
    backgroundColor: 'rgba(0,0,0,0.2)',
    borderRadius: 8,
    borderWidth: 1,
    // borderBottomColor: '#1e1e1e',
    // borderTopColor: '#373737',
    // borderLeftColor: '#373737',
    // borderRightColor: '#373737',
    borderBottomColor: '#8f8f8f',
    borderTopColor: '#8f8f8f',
    borderLeftColor: '#8f8f8f',
    borderRightColor: '#8f8f8f',
    color: 'white',
    fontFamily: 'NotoSans_500Medium',
    fontSize: 16,
    lineHeight: 20,
  },
  row_otp: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  col_otp: {
    width: '8%',
    flexGrow: 1,
  },
  text_otp: {
    fontFamily: 'NotoSans_400Regular',
    fontSize: 14,
    color: '#373737'
  },
  input_otp: {
    paddingBottom: 10,
    paddingTop: 10,
    paddingLeft: 5,
    paddingRight: 5,
    backgroundColor: 'rgba(0,0,0,0.2)',
    borderRadius: 8,
    borderWidth: 1,
    // borderBottomColor: '#1e1e1e',
    // borderTopColor: '#373737',
    // borderLeftColor: '#373737',
    // borderRightColor: '#373737',
    borderBottomColor: '#8f8f8f',
    borderTopColor: '#8f8f8f',
    borderLeftColor: '#8f8f8f',
    borderRightColor: '#8f8f8f',
    textAlign: 'center',
    width: '100%',
    color: 'white',
    fontFamily: 'NotoSans_500Medium',
    fontSize: 16,
    lineHeight: 20,
  },
  text_enter: {
    textAlign: 'center',
    fontFamily: 'NotoSans_400Regular',
    fontSize: 14,
    color: 'white',
    marginBottom: 5,
  },
  text_email_code: {
    textAlign: 'center',
    fontFamily: 'NotoSans_400Regular',
    fontSize: 14,
    color: '#757575',
  },

  buttonBackWrapper: {
    position: 'absolute',
    left: 20,
    top: 20,
  },
  buttonBack: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
});