name: Build production manual

on:
  workflow_dispatch:
    inputs:
      message:
        type: string
        required: false
        default: "Manual production build"

jobs:
  build_android_production:
    name: Build Android production
    type: build
    params:
      platform: android
      profile: production
      message: ${{ inputs.message }}